[theme]
base = "dark"
primaryColor = "#F4A7BB"
backgroundColor = "#141414"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#FFFFFF"
borderColor = "#2E2E2E"
baseFontSize = 16
baseRadius = "full"
font = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap, sans-serif"
headingFont = "League Gothic:https://fonts.googleapis.com/css2?family=League+Gothic&display=swap, sans-serif"

[client]
toolbarMode = "viewer"
showErrorDetails = false
showSidebarNavigation = false

[browser]
gatherUsageStats = false

[server]
headless = true
